name: nat_l10n_platform_interface
description: Utility functions for calling localized Locales, Timezones & Currencies from the underlying native platform.
version: 1.1.0
repository: https://github.com/GoldenSoju/nat_l10n/tree/master/nat_l10n_platform_interface

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter