name: nat_l10n_platform_interface
description: Utility functions for calling localized Locales, Timezones & Currencies from native.
version: 0.0.1
homepage: k

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter