name: nat_l10n
description: Utility functions for calling localized Locales, Timezones & Currencies from native.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  nat_l10n_platform_interface:
    path: ../nat_l10n_platform_interface

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.2

flutter:
  plugin:
    platforms:
      android:
        package: com.cloudia9.nat_l10n
        pluginClass: NatL10nPlugin
      ios:
        pluginClass: NatL10nPlugin
