name: nat_l10n
description: Utility functions for calling localized Locales, Time Zones & Currencies from the underlying native platform.
version: 1.1.0
repository: https://github.com/GoldenSoju/nat_l10n/tree/master/nat_l10n

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  nat_l10n_platform_interface: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    platforms:
      android:
        package: com.cloudia9.nat_l10n
        pluginClass: NatL10nPlugin
      ios:
        pluginClass: NatL10nPlugin
